language: python
sudo: false
python:
- '2.7'
matrix:
  allow_failures:
  - python: '2.6'
  - python: '3.4'
  - python: pypy
addons:
  apt:
    packages:
    - gdal-bin
    - python-numpy
    - python-scipy
    - python-matplotlib
    - ipython
    - ipython-notebook
    - python-pandas
    - python-sympy
    - python-nose
    - build-essential
    - python-dev
    - gfortran
    - cython
install:
- pip install -r requirements.txt
- pip install coveralls
- pip install nose
script:
- nosetests
after_success: coveralls
os:
# - osx
- linux
