language: python
sudo: false
python:
- '2.7'
virtualenv:
  system_site_packages: true
matrix:
  allow_failures:
  - python: '2.6'
  - python: '3.4'
  - python: pypy
  - os: osx
addons:
  apt:
    packages:
    - libgdal-dev
    - libgdal1h
    - libgdal1-dev
    - gdal-bin
    - python-gdal
    - python-numpy
    - python-scipy
    - python-matplotlib
    - python-pandas
    - python-sympy
    - python-nose
    - build-essential
    - python-dev
    - gfortran
    - cython
install:
- pip install -r requirements.txt
- pip install coveralls
- pip install nose
script:
- nosetests
after_success: coveralls
os:
- linux
- osx
